describe('interview practice', () => {
  it('unlocks the room and starts a category session', () => {
    cy.intercept('GET', '/api/session', { authenticated: false, aiAvailable: true })
    cy.intercept('POST', '/api/session', { authenticated: true, aiAvailable: true })
    cy.visit('/')
    cy.get('#password').type('test-password')
    cy.contains('button', 'Enter').click()
    cy.contains('h1', 'Practice the answer.')
    cy.contains('button', 'Personal narrative & motivation').click()
    cy.contains('button', 'Record answer')
    cy.contains('1 / 4')
  })

  it('falls back to timed self-review when AI is not configured', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('button', 'Personal narrative & motivation').click()
    cy.contains('button', 'Start answer timer').click()
    cy.contains('button', 'Finish & reveal guide').click()
    cy.contains('h2', 'Compare your answer with the guide')
    cy.contains('No AI score')
    cy.get('.beat-detail summary').first().click()
    cy.get('.beat-detail').first().should('have.attr', 'open')
    cy.get('.beat-detail').first().contains('From the reference answer')
  })

  it('opens the settings study guide and filters the full question bank', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('a', 'Settings').click()
    cy.contains('h1', 'Shape the session.')
    cy.contains('95 shown')
    cy.get('input[type="search"]').type('idempotency')
    cy.contains('Design an API between a transaction UI and its backend.')
    cy.get('#session-size').select('10')
    cy.window().should((win) => {
      const saved = JSON.parse(win.localStorage.getItem('interview-room.practice.v1') || '{}')
      if (saved.preferences?.sessionSize !== 10) {
        throw new Error('Session-size preference has not persisted yet')
      }
    })
  })

  it('shows technical cards in the category and study guide with readable code', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('button', 'Technical fundamentals').click()
    cy.contains('1 / 5')
    cy.contains('Fundamentals')
    cy.contains('button', 'All questions').click()
    cy.contains('a', 'Settings').click()
    cy.get('select[aria-label="Filter by category"]').select('technical-fundamentals')
    cy.contains('60 shown')
    cy.get('input[type="search"]').type('What prints?')
    cy.contains('1 shown')
    cy.get('.study-card .question-code').first().should('contain.text', 'console.log')
  })

  it('includes the new category in mixed practice', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('a', 'Settings').click()
    cy.get('#session-size').select('all')
    cy.contains('a', 'Back to practice').click()
    cy.contains('button', 'Start mixed practice').click()
    cy.contains('1 / 95')
  })

  it('practices payment reliability and filters its fifteen study cards', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('button', 'Payment reliability & incident response').click()
    cy.contains('1 / 5')
    cy.contains('Payments')
    cy.contains('button', 'All questions').click()
    cy.contains('a', 'Settings').click()
    cy.get('select[aria-label="Filter by category"]').select('payment-reliability')
    cy.contains('15 shown')
    cy.get('input[type="search"]').type('transactional outbox')
    cy.contains('1 shown')
    cy.contains('What problem does a transactional outbox solve in a payment system?')
  })

  it('expands a payment beat into focused guidance', () => {
    cy.intercept('GET', '/api/session', { authenticated: true, aiAvailable: false })
    cy.visit('/')
    cy.contains('a', 'Settings').click()
    cy.get('input[role="switch"]').first().uncheck({ force: true })
    cy.contains('a', 'Back to practice').click()
    cy.contains('button', 'Payment reliability & incident response').click()
    cy.contains('h1', 'What should an idempotency key represent in a payment flow?')
    cy.contains('button', 'Start answer timer').click()
    cy.contains('button', 'Finish & reveal guide').click()
    cy.contains('.beat-detail summary', 'One stable key per logical payment intent').click()
    cy.contains('HTTP attempts are only delivery attempts')
    cy.contains('.beat-detail summary', 'Persist and enforce it server-side').click()
    cy.get('.beat-detail[open]').should('have.length', 2)
  })
})
